# Generated by Django 3.0.4 on 2020-06-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('', '--Pilih Status--'), ('1', 'ADMIN'), ('2', 'STAFF')], default='', max_length=100, null=True),
        ),
    ]
