# Generated by Django 3.0.4 on 2020-06-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
