# Generated by Django 3.0.4 on 2020-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('ppm_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm CH4')),
                ('ppm_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm C2H4')),
                ('ppm_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm C2H2')),
                ('persen_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%CH4')),
                ('persen_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H4')),
                ('persen_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H2')),
                ('fault', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fault')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Level')),
                ('bias', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, null=True, verbose_name='No')),
                ('ppm_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm CH4')),
                ('ppm_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm C2H4')),
                ('ppm_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm C2H2')),
                ('persen_ch4', models.CharField(max_length=50, null=True, verbose_name='%CH4')),
                ('persen_c2h4', models.CharField(max_length=50, null=True, verbose_name='%C2H4')),
                ('persen_c2h2', models.CharField(max_length=50, null=True, verbose_name='%C2H2')),
                ('fault', models.CharField(max_length=50, null=True, verbose_name='Fault')),
                ('hasil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hasil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, null=True, verbose_name='No')),
                ('f1', models.CharField(max_length=50, null=True, verbose_name='f1')),
                ('f2', models.CharField(max_length=50, null=True, verbose_name='f2')),
                ('f3', models.CharField(max_length=50, null=True, verbose_name='f3')),
                ('f4', models.CharField(max_length=50, null=True, verbose_name='f4')),
                ('f5', models.CharField(max_length=50, null=True, verbose_name='f5')),
                ('f6', models.CharField(max_length=50, null=True, verbose_name='f6')),
                ('f7', models.CharField(max_length=50, null=True, verbose_name='f7')),
                ('hasil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hasil')),
                ('aktual', models.CharField(max_length=50, null=True, verbose_name='Aktual')),
                ('akurasi', models.CharField(max_length=50, null=True, verbose_name='Akurasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='HasilTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Level')),
                ('n_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%CH4')),
                ('n_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H4')),
                ('n_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H2')),
                ('fault', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fault')),
                ('kelas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kelas')),
                ('alpha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alpha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('lamda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lambda')),
                ('sigma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sigma')),
                ('complexity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complexity')),
                ('gamma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gamma')),
                ('iterasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iterasi')),
            ],
        ),
    ]
