# Generated by Django 3.0.4 on 2020-06-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True, verbose_name='Kode')),
                ('desc', models.CharField(max_length=50, null=True, verbose_name='Keterangan')),
            ],
        ),
    ]
