# Generated by Django 3.0.4 on 2020-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faultdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultdesc',
            name='desc',
            field=models.CharField(max_length=200, null=True, verbose_name='Keterangan'),
        ),
    ]
