# Generated by Django 3.0.4 on 2020-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200626_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultdesc',
            name='desc',
            field=models.CharField(max_length=300, null=True, verbose_name='Keterangan'),
        ),
    ]
