# Generated by Django 3.0.4 on 2020-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200626_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='hasil_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hasil'),
        ),
    ]
