# Generated by Django 3.0.4 on 2020-06-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diagnosis_hasil_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatesting',
            name='fault',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fault'),
        ),
    ]
